name: Commit

on:
  push:
    branches:
      - '!master'
  pull_request:
    branches:
      - master

env:
  CI: true
  CARGO_TERM_COLOR: always

jobs:
  Setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: cargo build

      - name: Run tests
        run: cargo test

  CI:
    runs-on: ubuntu-latest
    needs:
      - Setup
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Build and push Docker image with Buildx (don't push on PR)
      # https://github.com/docker/build-push-action
      - name: Build docker image for ${{ matrix.producers.binary }}
        uses: docker/build-push-action@2cdde995de11925a030ce8070c3d77a52ffcf1c0
        with:
          context: .
          push: false
          tags: dimitrmo/rhiaqey-producer-owm:latest
          build-args: |
            BINARY=rhiaqey-producer-owm
